name: Unit Tests
on: [ push, pull_request ]
jobs:
  framelix-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: [ '8.1' ]
        phpunit-versions: [ 'latest' ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_database
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, exif, fileinfo, mysqli, sockets, json, curl, simplexml,zip, openssl
          coverage: xdebug
          tools: phpunit
      - name: Copy Config for Github Actions
        run: |
          php -r "file_exists('modules/FramelixUnitTests/config/config-editable.php') || copy('modules/FramelixUnitTests/config/config-editable-github-actions.php', 'modules/FramelixUnitTests/config/config-editable.php');"
      - name: Run Unit Tests
        run: phpunit --coverage-text --bootstrap modules/FramelixUnitTests/tests/_bootstrap.php --configuration modules/FramelixUnitTests/tests/phpunit.xml