name: Framelix Unit Tests
on:
  push:
  pull_request:
  repository_dispatch:
    types: [ run_test ]
jobs:
  framelix-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout framelix-docker repository
        uses: actions/checkout@v2
        with:
          repository: NullixAT/framelix-docker

      - name: Checkout framelix-tests repository
        uses: actions/checkout@v2
        with:
          repository: NullixAT/framelix-tests
          path: app

      - name: Checkout framelix-core repository
        uses: actions/checkout@v2
        with:
          repository: NullixAT/framelix-core
          path: app/modules/Framelix

      - name: Setup environment
        run: |
          cp config/env-default .env
          chmod -R 0777 app

      - name: Start docker containers
        run: docker-compose up -d --build

      - name: Setup Composer inside docker
        run: |
          docker-compose exec -T phpfpm bash -c "cd /framelix && sh composer-setup.sh" 
          docker-compose exec -T phpfpm bash -c "cd /framelix && php composer.phar install"

      - name: Run Unit Tests
        run: ./app/phpunit.sh

      - name: Set Unit Test Coverage ENV
        run: php hooks/after-phpunit.php

      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 2e4ba189fbb1a23bff14e73cb893bc3e
          filename: framelix-unit-tests-coverage-data.json
          label: CodeCoverage
          message: ${{ env.COVERAGE }}
          color: orange

      - name: Run PhpStan Static Analysis
        run: ./app/phpstan.sh

      - name: Stop containers
        if: always()
        run: docker-compose down