name: Unit Tests
on: [ push, pull_request ]
jobs:
  framelix-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: [ 'ubuntu-latest' ]
        php-versions: [ '8.1' ]
        phpunit-versions: [ 'latest' ]
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.1'
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_database
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, exif, fileinfo, mysqli, sockets, json, curl, simplexml,zip, openssl
      - name: Setup NodeJS
        uses: actions/setup-node@v2
      - name: NPM Install
        run: cd modules/Framelix && npm install
      - name: Copy Config for Github Actions
        run: |
          php -r "file_exists('modules/FramelixTests/config/config-editable.php') || copy('modules/FramelixTests/config/config-editable-github-actions.php', 'modules/FramelixTests/config/config-editable.php');"
      - name: Update Composer
        run: sudo composer self-update --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: Run Unit Tests
        run: vendor/bin/phpunit --coverage-clover clover.xml  --bootstrap modules/FramelixTests/tests/_bootstrap.php --configuration modules/FramelixTests/tests/_phpunit.xml
      - name: Set Unit Test Coverage ENV
        run: php hooks/after-phpunit.php
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 2e4ba189fbb1a23bff14e73cb893bc3e
          filename: framelix-unit-tests-coverage-data.json
          label: CodeCoverage
          message: ${{ env.COVERAGE }}
          color: orange
      - name: Run PhpStan Static Analysis
        run: vendor/bin/phpstan analyse --memory-limit 1G